#! /bin/sh -x

apt-get install --no-install-recommends -y \
  python-sphinx python-sphinxcontrib.blockdiag python-sphinxcontrib.actdiag \
  python-sphinxcontrib.seqdiag python-sphinxcontrib.nwdiag \
  python-pip python-pil make

