##
## mkimage.sh wrapper.
## usage:
##
##   rake mkimage TAG=minimum2scp/debian-jessie:latest
##
#
require 'tmpdir'
require 'rake/clean'

CLOBBER.include 'build.log', 'debian-packages.txt', 'README.md'

task :default => ['README.md']

desc 'create mkimage.sh log file'
file 'build.log' => [:mkimage]

desc 'run mkimage.sh'
task :mkimage  do
  tag_option = ENV['TAG'] ? "-t #{ENV['TAG']}" : ''
  debootstrap_options = %w[
    --arch=amd64 --variant=minbase --components=main --include=iproute2,inetutils-ping
    jessie http://ftp.jp.debian.org/debian
  ].join(' ')
  env = ENV.select{|k,v| ['TMPDIR', 'http_proxy'].include?(k) }.map{|k,v| "#{k}=#{v}"}.join(' ')
  sh "sudo #{env} /usr/share/docker.io/contrib/mkimage.sh #{tag_option} debootstrap #{debootstrap_options} | tee build.log"
end

desc 'update debian-packages.txt'
file 'debian-packages.txt' => ['build.log'] do |t|
  tag = ENV['TAG'] || 'minimum2scp/debian-jessie:latest'
  sh %Q[docker run --rm #{tag} bash -c "LANG=C COLUMNS=120 dpkg -l" > #{t.name}]
end

desc 'update README.md'
file 'README.md' => ['README.md.erb', 'debian-packages.txt'] do |t|
  sh "erb #{t.prerequisites.first} > #{t.name}"
end
