#! /bin/sh -x

export DEBIAN_FRONTEND=noninteractive

##
## install ruby and build tool
##
apt-get install --no-install-recommends -y \
  ruby ruby-dev bundler build-essential

##
## install tdiary gem
##
gem install -N tdiary

##
## create new diary
##

sudo -u debian /build/scripts/user-scripts/create-new-diary.sh
install -m 644 -o debian -g debian -p /build/scripts/conf/tdiary.conf /home/debian/diary/tdiary.conf
install -m 755 -o debian -g debian -p /build/scripts/conf/start.sh    /home/debian/diary/start.sh

##
## install supervisor
##
apt-get install -y --no-install-recommends supervisor

##
## add tdiary to supervisor
##
install -m 644 -o root -g root -p /build/scripts/conf/supervisor-tdiary.conf /etc/supervisor/conf.d/tdiary.conf

