source 'https://rubygems.org'

gem 'serverspec'
gem 'specinfra', :github => 'minimum2scp/specinfra', :branch => 'fix/debian-v8-with-sysvinit'
gem 'docker-api'
gem 'pry'
gem 'thor'
gem 'sequel'
gem 'sqlite3'
gem 'text-table'
