require 'csv'
require 'erb'
require 'json'
require 'rake/clean'

CLOBBER.include 'README.md', 'debian-packages.json'

task :default => ['README.md']

desc 'update debian-packages.json'
file 'debian-packages.json' do |t|
  tag = ENV['TAG'] || 'minimum2scp/baseimage-jessie:latest'
  tsv_file = File.basename(t.name, ".json") + ".tsv"
  fields = %w[
    Architecture Conflicts Breaks Depends Enhances Essential Installed-Size Origin Package
    Pre-Depends Priority Provides Recommends Replace Section Status Suggests Version
    binary:Package binary:Summary db:Status-Abbrev db:Status-Want db:Status-Status db:Status-Eflag
    source:Package source:Version
  ]
  field_fmt = fields.map{|f| "${#{f}}"}.join("\\t") + "\\n"
  sh %Q[docker run --rm #{tag} dpkg-query -f '#{field_fmt}' -W > #{tsv_file}], :verbose => false
  packages = CSV.read(tsv_file, :col_sep => "\t").map{ |row| Hash[fields.zip(row)] }
  rm tsv_file, :verbose => false
  File.open(t.name, "w") do |fh|
    fh << JSON.pretty_generate(packages)
  end
end

desc 'update README.md'
file 'README.md' => ['README.md.erb', 'debian-packages.json'] do |t|
  packages = JSON.parse(File.read('debian-packages.json'))
  File.open(t.name, "w") do |fh|
    fh << ERB.new(File.read('README.md.erb'), nil, '-').result(binding)
  end
end

