#! /bin/bash

#set -e
#set -x

## rm /etc/nginx/conf.d/default.conf
if [ -f /etc/nginx/conf.d/default.conf ]; then
  rm /etc/nginx/conf.d/default.conf
fi

## create /etc/nginx/conf.d/backends.conf
echo "upstream tdiary {" > /tmp/backend.conf
export -p | grep -E 'declare -x TDIARY_[0-9]+_PORT_80_TCP_ADDR=' | while read var; do
  ipaddr=`echo $var | cut -d= -f2 `
  ipaddr=${ipaddr//\"/}
  echo "  server ${ipaddr}:80;" >> /tmp/backend.conf
done
echo "}" >> /tmp/backend.conf
#cat /tmp/backend.conf
install -m 644 -o root -g root -p /tmp/backend.conf /etc/nginx/conf.d/backend.conf

exec "$@"
