tdiary:
  image: minimum2scp/magellan-tdiary:0.1.2
  links:
    - db
    - cache
  command: >
    bundle exec passenger start -e production -p 80
    --pid-file tmp/passenger.pid --load-shell-envvars --static-files-dir public
  environment:
    - MYSQL_USERNAME=tdiary
    - MYSQL_PASSWORD=tdiary
    - MYSQL_DATABASE=tdiary
    #- TDIARY_BASIC_AUTH_USERNAME=tdiary
    #- TDIARY_BASIC_AUTH_PASSWORD=tdiary

db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=tdiary
    - MYSQL_PASSWORD=tdiary
    - MYSQL_DATABASE=tdiary
  volumes:
    #- ./volumes/mysql-data:/var/lib/mysql:rw
    - ./volumes/mysql-conf/charset.cnf:/etc/mysql/conf.d/charset.cnf:ro

cache:
  image: redis:3.0

