##
## mkimage.sh wrapper.
## usage:
##
##   rake mkimage TAG=minimum2scp/debian:latest
##
#
require 'tmpdir'

task :default => [:mkimage]

desc "run mkimage.sh"
task :mkimage  do
  tag_option = ENV['TAG'] ? "-t #{ENV['TAG']}" : ""
  debootstrap_options = %w[
    --arch=amd64 --variant=minbase --include=iproute2,inetutils-ping
    sid http://ftp.jp.debian.org/debian
  ].join(" ")
  env = ENV.select{|k,v| ['TMPDIR', 'http_proxy'].include?(k) }.map{|k,v| "#{k}=#{v}"}.join(" ")
  sh "sudo #{env} /usr/share/docker.io/contrib/mkimage.sh #{tag_option} debootstrap #{debootstrap_options}"
end

