##
## mkimage.sh wrapper.
## usage:
##
##   rake mkimage TAG=minimum2scp/debian:latest
##
#
require 'tmpdir'

docker_dir = File.expand_path("docker", Dir.tmpdir)

task :default => [:mkimage]

desc "git clone docker.git"
directory docker_dir do
  sh "git clone git@github.com:docker/docker.git #{docker_dir}"
end

desc "run mkimage.sh"
task :mkimage  => [docker_dir] do
  tag_option = ENV['TAG'] ? "-t #{ENV['TAG']}" : ""
  debootstrap_options = %w[
    --arch=amd64 --variant=minbase --include=iproute2,inetutils-ping
    sid http://ftp.jp.debian.org/debian
  ].join(" ")
  env = ENV.select{|k,v| ['TMPDIR', 'http_proxy'].include?(k) }.map{|k,v| "#{k}=#{v}"}.join(" ")
  sh "sudo #{env} #{docker_dir}/contrib/mkimage.sh #{tag_option} debootstrap #{debootstrap_options}"
end

