##
## mkimage.sh wrapper.
## usage:
##
##   rake mkimage TAG=minimum2scp/debian:latest
##
#
require 'tmpdir'
require 'rake/clean'

CLOBBER.include 'debian-packages.txt', 'README.md'

task :default => [:mkimage, 'README.md']

desc "run mkimage.sh"
task :mkimage  do
  tag_option = ENV['TAG'] ? "-t #{ENV['TAG']}" : ""
  debootstrap_options = %w[
    --arch=amd64 --variant=minbase --include=iproute2,inetutils-ping
    sid http://ftp.jp.debian.org/debian
  ].join(" ")
  env = ENV.select{|k,v| ['TMPDIR', 'http_proxy'].include?(k) }.map{|k,v| "#{k}=#{v}"}.join(" ")
  sh "sudo #{env} /usr/share/docker.io/contrib/mkimage.sh #{tag_option} debootstrap #{debootstrap_options}"
end

desc 'update debian-packages.txt'
file 'debian-packages.txt' do |t|
  tag = ENV['TAG'] || 'minimum2scp/debian:latest'
  sh %Q[docker run --rm #{tag} bash -c "LANG=C COLUMNS=120 dpkg -l" > #{t.name}]
end

desc 'update README.md'
file 'README.md' => ['README.md.erb', 'debian-packages.txt'] do |t|
  require 'erb'
  File.open(t.name, 'w'){|fh|
    fh << ERB.new(File.read(t.prerequisites.first)).result
  }
end
