FROM minimum2scp/baseimage:next

MAINTAINER YAMADA Tsuyoshi <tyamada@minimum2scp.org>

RUN apt-get update && /opt/custom-installers/consul/install.sh
ENTRYPOINT ["/opt/init-wrapper/sbin/entrypoint.sh"]
CMD ["/sbin/init"]

