#! /bin/sh -x

export DEBIAN_FRONTEND=noninteractive

cat <<EOS > /etc/apt/sources.list
##
## stable
##

#deb     http://ftp.jp.debian.org/debian/ stable main non-free contrib
#deb-src http://ftp.jp.debian.org/debian/ stable main non-free contrib

#deb     http://security.debian.org/ stable/updates main contrib non-free
#deb-src http://security.debian.org/ stable/updates main contrib non-free

#deb     http://ftp.jp.debian.org/debian/ stable-updates main contrib non-free
#deb-src http://ftp.jp.debian.org/debian/ stable-updates main contrib non-free

##
## testing
##

#deb     http://ftp.jp.debian.org/debian/ testing main non-free contrib
#deb-src http://ftp.jp.debian.org/debian/ testing main non-free contrib

##
## sid
##

deb     http://ftp.jp.debian.org/debian/ sid main non-free contrib
#deb-src http://ftp.jp.debian.org/debian/ sid main non-free contrib

##
## experimental
##

#deb     http://ftp.jp.debian.org/debian/ experimental main non-free contrib
#deb-src http://ftp.jp.debian.org/debian/ experimental main non-free contrib
EOS

apt-get update
apt-get dist-upgrade -y --fix-missing --fix-broken

