require 'rake/clean'
require 'pathname'

build_dir = Pathname.new(File.expand_path('build', __dir__))
tmp_dir = build_dir + 'tmp'
pbsetup_script = tmp_dir + 'pbsetup.sh' ## NOTE: pbsetup.sh is private script

relpath = ->(path){ path.relative_path_from(Pathname(__dir__)).to_s }
CLEAN << relpath[tmp_dir]

task :default => :"docker-build"

desc 'build docker image'
task :"docker-build" => relpath[pbsetup_script] do
  tag_option = ENV['TAG'] ? "-t #{ENV['TAG']}" : ""
  sh "docker build #{tag_option} ."
end

desc "create build/tmp"
directory relpath[tmp_dir]

desc "setup build/tmp/pbsetup.sh"
file relpath[pbsetup_script] => [ relpath[tmp_dir] ] do
  sh "pbsetup.sh #{build_dir}"
end

